version: "3.7"
services:
  www:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
    - ./app/:/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  frontend:
    build: ./frontend
    command: ./node_modules/.bin/parcel watch bundles-src/index.js --dist-dir bundles --public-url="./"
    volumes:
    - frontend_volume:/app/frontend
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
volumes:
  postgres_volume:
  frontend_volume:
