version: '3.7'

services:
  front:
    build:
      context: ./front
      dockerfile: Dockerfile.front
    container_name: burger_front
    volumes:
      - app_volume:/usr/src/app/front
    volumes_from:
      - web:rw
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: sh -c "python manage.py migrate       --noinput                             &&
                    gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - app_volume:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    expose:
      - 8000
    env_file:
      - ./.env
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
      - media_volume:/usr/src/app/media
    ports:
      - 80:80
    depends_on:
      - web
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env
volumes:
  app_volume:
  static_volume:
  media_volume:
  postgres_volume:
