version: '3.7'

services:
  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    volumes:
      - app_volume:/app
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: sh -c "python manage.py collectstatic --noinput                             &&
                    python manage.py migrate       --noinput                             &&
                    gunicorn star_burger.wsgi:application --bind 127.0.0.1:8000"
    volumes:
      - app_volume:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - 8000:8000
    expose:
      - 8000
    env_file:
      - ./.env-prod
    depends_on:
      - front
      - db
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - 80:80
    depends_on:
      - web
  db:
    image: postgres:14.0-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ./.env-prod
volumes:
  app_volume:
  static_volume:
  media_volume:
  postgres_volume:
