ARG NODEJS_VERSION=16

FROM node:${NODEJS_VERSION}-buster-slim

WORKDIR /app/

COPY ./assets/ /assets/
COPY ./package.json package.json
COPY ./package-lock.json package-lock.json

RUN npm ci --include=dev

COPY ./bundles-src ./bundles-src

RUN ./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
