# Generated by Django 3.2 on 2022-06-01 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(db_index=True, max_length=100, verbose_name='Адрес')),
                ('lat', models.FloatField(db_index=True, verbose_name='Широта')),
                ('lon', models.FloatField(db_index=True, verbose_name='Долгота')),
                ('created_at', models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Местоположение',
                'verbose_name_plural': 'Местоположения',
            },
        ),
    ]
