# Generated by Django 3.2 on 2022-06-02 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Адрес'),
        ),
    ]
