# Generated by Django 3.2 on 2022-06-06 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locationdata', '0003_auto_20220606_0951'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderLocation',
            new_name='Location',
        ),
        migrations.DeleteModel(
            name='RestaurantLocation',
        ),
    ]
