# Generated by Django 3.2 on 2022-06-21 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locationdata', '0005_auto_20220621_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='created_at',
        ),
        migrations.AddField(
            model_name='location',
            name='creation_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата добавления записи'),
        ),
    ]
