# Generated by Django 3.2 on 2022-05-23 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0008_alter_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='last_name',
            new_name='lastname',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='phone',
            new_name='phonenumber',
        ),
    ]
