# Generated by Django 3.2 on 2022-05-26 11:15

from django.db import migrations


def set_product_price(apps, shema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for order in OrderItem.objects.iterator():
        order.price = order.product.price
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0011_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(set_product_price),
    ]
