# Generated by Django 3.2 on 2022-05-27 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0013_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('unprocessed', 'Необработынный'), ('processed', 'Обработанный')], default=0, max_length=12, verbose_name='Статус'),
            preserve_default=False,
        ),
    ]
