# Generated by Django 3.2 on 2022-05-20 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0006_auto_20220519_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='amount',
            field=models.IntegerField(verbose_name='Количество'),
        ),
    ]
