# Generated by Django 3.2 on 2022-05-24 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0009_auto_20220523_0600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='amount',
            new_name='quantity',
        ),
    ]
