# Generated by Django 3.2 on 2022-05-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0014_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('unprocessed', 'Необработынный'), ('processed', 'Обработанный')], default='unprocessed', max_length=12, verbose_name='Статус'),
        ),
    ]
