# Generated by Django 3.2 on 2022-05-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0020_auto_20220527_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cashless', 'Безналичный'), ('cash', 'Наличные')], db_index=True, max_length=12, verbose_name='Способ оплаты'),
        ),
    ]
