# Generated by Django 3.2 on 2022-05-28 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0022_alter_orderitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restorans', to='foodcartapp.restaurant', verbose_name='Ресторан'),
        ),
    ]
