# Generated by Django 3.2 on 2022-06-21 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0024_alter_orderitem_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='restaurant',
            new_name='restaurant_with_order',
        ),
    ]
