# Generated by Django 3.2 on 2022-06-21 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locationdata', '0004_auto_20220606_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, db_index=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='location',
            name='lon',
            field=models.FloatField(blank=True, db_index=True, verbose_name='Долгота'),
        ),
    ]
